import json

from HanTa import HanoverTagger as ht
tagger_en = ht.HanoverTagger('morphmodel_en.pgz')
tagger_de = ht.HanoverTagger('morphmodel_ger.pgz')


lexicon = {
      "individual": [
      "equal opportunity",
      "equal conditions", 
      "equal chances",
      "opportunity",
      "opportunities",
      "participate",
      "participation",
      "contribute",
      "contribution",
      "individual",
      "individuality",
      "individualized",
      "individually",
      "self",
      "oneself",
      "member",
      "members",
      "person",
      "personal",
      "personalize",
      "personalized",
      "right",
      "freedom",
      "autonomy",
      "autonomous",
      "identity",
      "identify",
      "background",
      "unique",
      "uniqueness",
      "uniquely",
      "talent",
      "skill",
      "handicap",
      "regardless of",
      "free from",
      "irrespective of",
      "on the grounds of",
      "no matter",
      "you",
      "merit",
      "tailor",
      "tailored",
      "cater",
      "catered",
      "everyone",
      "barriers",
      "innate",
      "to be",
      "they are"
    ],
    "collective": [
        "justice",
        "community",
        "collaboration",
        "collaborative",
        "collaborate",
        "belonging",
        "unity",
        "cohesive",
        "cohesion",
        "public",
        "unity",
        "unitfy",
        "united",
        "multicultural",
        "tradition",
        "tolerant",
        "tolerance",
        "marginalize",
        "sustainability",
        "sustainable",
        "solidarity",
        "ally",
        "allyship",
        "collective",
        "share",
        "shared",
        "mutual",
        "citizenship",
        "global citizenship",
        "team",
        "representation",
        "represented",
        "society",
        "oppression",
        "oppressed",
        "cultural",
        "culture",
        "underrepresented",
        "relations",
        "relationships",
        "population",
        "populations",
        "group",
        "groups",
        "close-knit",
        "understanding",
        "connection",
        "connections",
        "connected",
        "connective",
        "world",
        "empathetic",
        "empathy",
        "visibility",
        "visible"
  ]
}


lexicon = {
    "individual": list(set([item[1] for item in tagger_en.tag_sent(lexicon["individual"])])),
    "collective": list(set([item[1] for item in tagger_en.tag_sent(lexicon["collective"])]))
}


# write lexicon to json file
with open("an_lexicon/data/lexicon.json", "w") as f:
    json.dump(lexicon, f, indent=4)
